filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: ""
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  username: elastic
  password: ${ELK_PASSWORD}
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  
setup.kibana:
  host: "kibana:5601"
  protocol: "http"
  path: "/kibana"
  username: elastic
  password: ${ELK_PASSWORD}

logging.json: true
logging.metrics.enabled: false